//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

pub use super::deck::Entity as Deck;
pub use super::game::Entity as Game;
pub use super::game_player::Entity as GamePlayer;
pub use super::player::Entity as Player;
