//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "enum")]
pub enum Enum {
    #[sea_orm(string_value = "waiting")]
    Waiting,
    #[sea_orm(string_value = "in_progress")]
    InProgress,
    #[sea_orm(string_value = "finished")]
    Finished,
}
